######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 25 02:03:25 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += test.cpp
